### ISSUE TITLE
Fix for configure_requires

### ISSUE THREAD

**Issue by plicease** [Getty/p5-alien-mpg123#1]
This dist has `Alien::Base` as a configure requires.  Please change this to `Alien::Base::ModuleBuild` to future proof this module.  For rationale, please see 

https://github.com/Perl5-Alien/Alien-Base/issues/157

**Comment by plicease** [comment]
btw- all that you need to do is do is make sure that Dist::Zilla::Plugin::Alien is of the latest version and do a release.

**Comment by plicease** [comment]
@getty, if you need any help merging some of these Alien PRs and uploading new versions, please let me know.  I would like to eventually split AB::ModuleBuild into its own distribution and applying this fix, these modules will continue to work when that happens.

**Comment by michal-josef-spacek** [comment]
What is fix for this issue? 
When i regenerate dist by dzill, there will be:
`"Alien::Base::ModuleBuild" => "0.002"`
instead of
`"Alien::Base" => "0.002"` (in 0.002 version)
in configure requires section

**Comment by plicease** [comment]
> What is fix for this issue? When i regenerate dist by dzill, there will be: `"Alien::Base::ModuleBuild" => "0.002"` instead of `"Alien::Base" => "0.002"` (in 0.002 version) in configure requires section

The fix is just that: to regenerate and release with a recent version of `Dist::Zilla::Plugin::Alien`.  Since the `dist.ini` isn't using that plugin directly to *ensure* that a recent version of `[Alien]` is used in  the build the `[@Author::GETTY]` bundle would have to require a recent version of `[Alien]` and the `dist.ini` for this dist should also be updated to require the new version of `[@Author::GETTY]`.

**Comment by michal-josef-spacek** [comment]
@plicease Great, thanks.
@Getty Could you please release module? :-)

**Comment by michal-josef-spacek** [comment]
@getty Or could you add me as maintainer of module? CPAN: SKIM

**Comment by Getty** [comment]
New version uploaded, added up Test::LoadAllModules requirement, the other one was automatically fixed through the [Alien] of the bundle.
